# Generated by Django 2.2.2 on 2019-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('private', models.BooleanField()),
                ('incompleto', models.BooleanField()),
                ('data_ultima_compra', models.DateField()),
                ('ticket_medio', models.FloatField()),
                ('ticket_ultima_compra', models.FloatField()),
                ('loja_mais_frequente', models.CharField(max_length=18)),
                ('loja_ultima_compra', models.CharField(max_length=18)),
                ('cpf_invalido', models.BooleanField()),
                ('loja_mais_frequente_valida', models.BooleanField()),
                ('loja_ultima_compra_valida', models.BooleanField()),
            ],
        ),
    ]
