# Generated by Django 2.2.2 on 2019-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsedata', '0003_auto_20190615_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='cnpj_loja_mais_frequente_valida',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='cnpj_loja_ultima_compra_valida',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='cpf_valido',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='data_ultima_compra',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='incompleto',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='loja_mais_frequente',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='loja_ultima_compra',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='private',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='ticket_medio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='ticket_ultima_compra',
            field=models.FloatField(null=True),
        ),
    ]
