# Generated by Django 2.2.2 on 2019-06-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsedata', '0004_auto_20190615_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='loja_mais_frequente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='loja_ultima_compra',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
